version: "3.5"

services:
    api01: &api
        container_name: api01
        build:
            context: .
        depends_on:
            - mysql
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "100MB"
    api02:
        <<: *api
        container_name: api02

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "50MB"

    mysql:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rinha
            MYSQL_USER: diego
            MYSQL_PASSWORD: 123456
        ports:
            - "3306:3306"
        volumes:
            - mysql-vol:/var/lib/mysql
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: "0.4"
                    memory: "300MB"

volumes:
    mysql-vol:

networks:
  rinha:
    driver: bridge